import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useUser, login, logout } from "../lib/firebase/auth";
import { addUser } from "../lib/firebase/db";

const Home: NextPage = () => {
  const user = useUser();
  const handleLogin = (): void => {
    login()
      .then((u) => addUser(u))
      .catch((error) => console.error(error));
  };

  const handleLogout = (): void => {
    logout().catch((error) => console.error(error));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Firebase demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>
        <div>
          {user !== null ? (
            <h2>{user.displayName}さんはログインしています</h2>
          ) : (
            <h2>ログインしていません</h2>
          )}
        </div>
        <div>
          {user !== null ? (
            <button onClick={handleLogout}>ログアウト</button>
          ) : (
            <button onClick={handleLogin}>ログイン</button>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
